// types of action
const Types = {
    SET_PERIOD:"SET_PERIOD",
    SET_CHARTS:"SET_CHARTS",
  
    LOAD_BATTERY_POWER_IN: "LOAD_BATTERY_POWER_IN",
    LOAD_BATTERY_POWER_OUT: "LOAD_BATTERY_POWER_OUT",
    FILTER_BATTERY_INOUT_DATES: "FILTER_BATTERY_INOUT_DATES",
    RESET_BATTERY_INTOUT_FILTER: "RESET_BATTERY_INTOUT_FILTER",
  
    LOAD_PANEL_CURRENT: "LOAD_PANEL_CURRENT",
    LOAD_USBHUB_CURRENT: "LOAD_USBHUB_CURRENT",
    LOAD_BATTERY_CURRENT: "LOAD_BATTERY_CURRENT",
    FILTER_CURRENT_DATES: "FILTER_CURRENT_DATES",
    RESET_CURRENT_FILTER: "RESET_CURRENT_FILTER",
  
    LOAD_BATTERY_VOLTAGE:'LOAD_BATTERY_VOLTAGE',
    FILTER_BATTERY_VOLTAGE:"FILTER_BATTERY_VOLTAGE",
    RESET_FILTER_BATTERY_VOLTAGE:"RESET_FILTER_BATTERY_VOLTAGE",
  
    LOAD_IRRADIANCE:"LOAD_IRRADIANCE",
    FILTER_IRRADIANCE:"FILTER_IRRADIANCE",
    RESET_FILTER_IRRADIANCE:"RESET_FILTER_IRRADIANCE",
  
    LOAD_TEMPERATURE:"LOAD_TEMPERATURE",
    FILTER_TEMPERATURE:"FILTER_TEMPERATURE",
    RESET_FILTER_TEMPERATURE:"RESET_FILTER_TEMPERATURE",
  
    LOAD_HUMIDITY:"LOAD_HUMIDITY",
    FILTER_HUMIDITY:"FILTER_HUMIDITY",
    RESET_FILTER_HUMIDITY:"RESET_FILTER_HUMIDITY",
  
    SET_DATES:'SET_DATES',
    RESET_DATES:'RESET_DATES',
  
    LOAD_TEMPS: "LOAD_TEMPS",
    SORT_TEMPS: "SORT_TEMPS",

    SET_SIZES:"SET_SIZES"
  };

  export default Types